In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
cd ./Documents/Python/UNZIP_FOR_NOTEBOOKS_FINAL/DATA

/Users/clementyuen/Documents/Python/UNZIP_FOR_NOTEBOOKS_FINAL/DATA


In [4]:
df = pd.read_csv('./Advertising.csv')

In [5]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
X = df.drop('sales',axis = 1)

In [7]:
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [8]:
y = df['sales']

In [9]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [26]:
a = scaler.fit(X_train)
a.get_params

<bound method BaseEstimator.get_params of StandardScaler()>

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train_scaled = scaler.transform(X_train)

In [27]:
X_test_scaled = scaler.transform(X_test)

In [28]:
from sklearn.linear_model import Ridge

In [30]:
model = Ridge(alpha=100)

In [32]:
model.fit(X_train_scaled,y_train)

Ridge(alpha=100)

In [33]:
y_prediction = model.predict(X_test_scaled)

In [34]:
y_prediction

array([15.34908128, 17.05755308, 12.73784965, 16.18231062, 10.85075815,
        9.87999576, 17.6105132 , 15.80786278, 11.32616781, 17.30158479,
       12.8883864 , 13.64670913, 13.71636726, 18.83377117, 17.38617584,
       11.59912699, 14.88899736, 10.07145317, 10.14692243, 17.90771073,
       10.25837266, 16.71492563, 20.57087744, 19.66643199, 10.14020781,
       13.40084066, 18.09910709, 10.80433113, 13.00876939, 13.79206361,
       12.73015096, 17.42108555, 11.50183684, 10.10362749, 16.18778637,
       10.45161746, 11.25953403, 10.42658319, 12.30681396, 11.82281519,
       14.75707677, 11.58372535, 12.01609545, 10.90016204, 12.55896716,
       11.62961585, 10.8495293 , 15.74187916, 14.09264772, 18.45114683,
       13.43419788, 14.05075373, 16.0980788 , 12.07046074, 13.15048011,
        8.75095421, 19.21013193, 12.92686996, 16.49277745, 14.83525505])

In [35]:
from sklearn.metrics import mean_squared_error

In [36]:
mean_squared_error(y_test,y_prediction)

7.34177578903413

In [38]:
model_two = Ridge(alpha=1)

In [41]:
model_two.fit(X_train_scaled,y_train)

Ridge(alpha=1)

In [42]:
y_prediction_two = model_two.predict(X_test_scaled)

In [43]:
mean_squared_error(y_test,y_prediction_two)

2.3190215794287514

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
df = pd.read_csv('Advertising.csv')

In [46]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_other, y_train, y_other = train_test_split(X, y, test_size=0.3, random_state=101)

In [49]:
# test_size = 0.5 (50% of 30% of other) --> test = 15% of all data
X_eval, X_test, y_eval, y_test = train_test_split(X_other, y_other, test_size = 0.5, random_state = 101)

In [50]:
len(df)

200

In [55]:
len(X_train), len(X_eval), len(X_test)

(140, 30, 30)

In [56]:
from sklearn.preprocessing import StandardScaler

In [61]:
scaler = StandardScaler()

In [63]:
scaler.fit(X_train)

StandardScaler()

In [64]:
X_train = scaler.transform(X_train)

In [65]:
X_test = scaler.transform(X_test)

In [66]:
X_eval = scaler.transform(X_eval)

In [67]:
from sklearn.linear_model import Ridge

In [68]:
model_one = Ridge(alpha=100)

In [69]:
model_one.fit(X_train, y_train)

Ridge(alpha=100)

In [75]:
y_eval_predictions = model_one.predict(X_eval)

In [71]:
from sklearn.metrics import mean_squared_error

In [76]:
mean_squared_error(y_eval, y_eval_predictions)

7.320101458823871

In [73]:
model_two = Ridge(alpha=1)

In [74]:
model_two.fit(X_train, y_train)

Ridge(alpha=1)

In [77]:
y_eval_predictions_two = model_two.predict(X_eval)

In [78]:
mean_squared_error(y_eval, y_eval_predictions_two)

2.3837830750569853

In [79]:
#im satisfied with model two's metrics, I'm going to conduct final test for reporting purposes
y_final_test_pred = model_two.predict(X_test)

In [80]:
mean_squared_error(y_test, y_final_test_pred)

2.2542600838005176

In [81]:
df = pd.read_csv('Advertising.csv')

In [82]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [84]:
X = df.drop('sales',axis =1)
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [86]:
y = df.sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [87]:
from sklearn.model_selection import train_test_split

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [90]:
from sklearn.preprocessing import StandardScaler

In [91]:
scaler = StandardScaler()

In [94]:
scaler.fit(X_train)

StandardScaler()

In [95]:
X_train_scaled = scaler.transform(X_train)

In [96]:
X_test_scaled = scaler.transform(X_test)

In [97]:
model = Ridge(alpha=100)

In [99]:
from sklearn.model_selection import cross_val_score

In [126]:
from sklearn.metrics import SCORERS

In [127]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [128]:
scores = cross_val_score(model,X_train_scaled, y_train, scoring='neg_mean_squared_error',cv = 5)

In [129]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

In [131]:
abs(scores.mean())

8.215396464543606

In [137]:
model2 = Ridge(alpha=1)

In [133]:
scores2 = cross_val_score(model2,X_train_scaled, y_train, scoring='neg_mean_squared_error',cv = 5)

In [134]:
scores2

array([-3.15513238, -1.58086982, -5.40455562, -2.21654481, -4.36709384])

In [135]:
abs(scores2.mean())

3.344839296530695

In [182]:
model3 = Ridge(alpha=0.1)

In [183]:
scores3 = cross_val_score(model3,X_train_scaled, y_train, scoring='neg_mean_squared_error',cv = 5)

In [184]:
scores3

array([-3.14074141, -1.6180669 , -5.37679032, -2.23944185, -4.34414511])

In [185]:
abs(scores3.mean())

3.3438371173739396

In [163]:
model2.fit(X_train_scaled,y_train)

Ridge(alpha=1)

In [164]:
y_final_test_predictions = model2.predict(X_test_scaled)

In [165]:
from sklearn.metrics import mean_squared_error

In [166]:
mean_squared_error(y_test, y_final_test_predictions)

2.3190215794287514

In [203]:
pd.DataFrame(model2.coef_,X.columns,columns=['betas'])

betas
TV         3.739618
radio      2.744777
newspaper  0.002688

In [178]:
from sklearn.linear_model import RidgeCV

In [179]:
modelR = RidgeCV()

In [193]:
modelR.fit(X_train_scaled,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]))

In [181]:
modelR.alpha_

0.1

In [186]:
modelR_pred = modelR.predict(X_test_scaled)

In [187]:
mean_squared_error(y_test,modelR_pred)

2.300652700356695

In [195]:
modelR.coef_

array([ 3.76333559,  2.76339947, -0.00593674])

In [200]:
pd.DataFrame(modelR.coef_, X.columns,columns=['coefficients'])

coefficients
TV             3.763336
radio          2.763399
newspaper     -0.005937

In [167]:
df = pd.read_csv('Advertising.csv')

In [168]:
X = df.drop('sales',axis=1)
y = df.sales

In [170]:
from sklearn.model_selection import train_test_split

In [171]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [169]:
from sklearn.preprocessing import StandardScaler

In [172]:
scaler.fit(X_train)

StandardScaler()

In [174]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [175]:
from sklearn.model_selection import cross_validate

In [218]:
model = Ridge(alpha = 0.1)

In [219]:
scores = cross_validate(model, X_train_scaled, y_train,scoring=['neg_mean_squared_error','neg_mean_absolute_error'],cv=10)

In [220]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [221]:
scores

{'fit_time': array([0.00201893, 0.00125885, 0.00201201, 0.00171304, 0.00121307,
        0.00062299, 0.00103092, 0.00060868, 0.00059271, 0.0005331 ]),
 'score_time': array([0.00095415, 0.00108409, 0.00112605, 0.00086403, 0.00038695,
        0.00038099, 0.00050497, 0.0003531 , 0.00036526, 0.00034785]),
 'test_neg_mean_squared_error': array([-2.97549169, -3.02345717, -2.21737608, -0.84369927, -3.43333928,
        -8.21561689, -1.94260309, -2.76140232, -4.96510913, -2.8426761 ]),
 'test_neg_mean_absolute_error': array([-1.45635146, -1.55334403, -1.24563999, -0.76163212, -1.41931076,
        -1.48706756, -1.09602224, -1.25822701, -1.57677256, -1.2238763 ])}

In [222]:
table = pd.DataFrame(scores)

In [223]:
table

fit_time  score_time  test_neg_mean_squared_error  \
0  0.002019    0.000954                    -2.975492   
1  0.001259    0.001084                    -3.023457   
2  0.002012    0.001126                    -2.217376   
3  0.001713    0.000864                    -0.843699   
4  0.001213    0.000387                    -3.433339   
5  0.000623    0.000381                    -8.215617   
6  0.001031    0.000505                    -1.942603   
7  0.000609    0.000353                    -2.761402   
8  0.000593    0.000365                    -4.965109   
9  0.000533    0.000348                    -2.842676   

   test_neg_mean_absolute_error  
0                     -1.456351  
1                     -1.553344  
2                     -1.245640  
3                     -0.761632  
4                     -1.419311  
5                     -1.487068  
6                     -1.096022  
7                     -1.258227  
8                     -1.576773  
9                     -1.223876

In [224]:
table[['test_neg_mean_squared_error','test_neg_mean_absolute_error']] = abs(table[['test_neg_mean_squared_error','test_neg_mean_absolute_error']])

In [225]:
table

fit_time  score_time  test_neg_mean_squared_error  \
0  0.002019    0.000954                     2.975492   
1  0.001259    0.001084                     3.023457   
2  0.002012    0.001126                     2.217376   
3  0.001713    0.000864                     0.843699   
4  0.001213    0.000387                     3.433339   
5  0.000623    0.000381                     8.215617   
6  0.001031    0.000505                     1.942603   
7  0.000609    0.000353                     2.761402   
8  0.000593    0.000365                     4.965109   
9  0.000533    0.000348                     2.842676   

   test_neg_mean_absolute_error  
0                      1.456351  
1                      1.553344  
2                      1.245640  
3                      0.761632  
4                      1.419311  
5                      1.487068  
6                      1.096022  
7                      1.258227  
8                      1.576773  
9                      1.223876

In [226]:
table.mean()

fit_time                        0.001160
score_time                      0.000637
test_neg_mean_squared_error     3.322077
test_neg_mean_absolute_error    1.307824
dtype: float64

In [227]:
model.fit(X_train_scaled, y_train)

Ridge(alpha=0.1)

In [228]:
y_final_pred = model.predict(X_test_scaled)

In [229]:
mean_squared_error(y_test, y_final_pred)

2.300652700356322

In [230]:
pwd

'/Users/clementyuen/Documents/Python/UNZIP_FOR_NOTEBOOKS_FINAL/DATA'